"""create favorite products table

Revision ID: 08d7d5bf9cf7
Revises: 224b4365e9ec
Create Date: 2025-11-01 18:06:26.371668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "08d7d5bf9cf7"
down_revision: Union[str, Sequence[str], None] = "224b4365e9ec"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "favorite_products",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "customer_id", "product_id", name="uq_customer_product_favorite"
        ),
    )
    op.create_index(
        op.f("ix_favorite_products_customer_id"),
        "favorite_products",
        ["customer_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_favorite_products_id"),
        "favorite_products",
        ["id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_favorite_products_id"), table_name="favorite_products"
    )
    op.drop_index(
        op.f("ix_favorite_products_customer_id"),
        table_name="favorite_products",
    )
    op.drop_table("favorite_products")
    # ### end Alembic commands ###
